### ISSUE TITLE
Post sobre Modernizr

### ISSUE THREAD

**Issue by datadiego** [escavdam/ultra-effective#47]
Necesitamos información acerca de [https://modernizr.com/docs/], crea un post explicando que es, en que nos puede ayudar en el desarrollo de nuestras aplicaciones y como podemos bajarlo y usarlo en un proyecto.

**Comment by MakramElghadir** [comment]
La informacion estaba escribida, exportado en MD y HTML y enviado al repositorio ultra effective tan un pull request.

Otras mas ?

**Comment by datadiego** [comment]
Cancelado! Han deprecado la web
